version: "3.3"

volumes:
  db-data:
    external: false

services:
  redis:
    image: 'redis:latest'
    container_name: video-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  db:
    image: postgres:14-alpine
    container_name: video-db
    volumes:
      - db-data:/var/lib/psql/db-data
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: unless-stopped

  app:
    image: video:latest
    container_name: video-app
    environment:
      SECRET_KEY_BASE: 10162d43557f2c9ec356be19d62e4b12
      POSTGRES_HOST: db
      POSTGRES_PORT: '5432'
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      FRONT_END_HOST: http://localhost:3000
    ports:
      - 3000:3000
    depends_on:
      - db
  
  react-app:
    image: client:latest
    container_name: video-react
    build: .
    ports:
      - 8080:8080
    environment:
      REACT_APP_SYNCFUSION_LICENSE_KEY: "adsfdsa"
      VITE_BASE_URL: "http://localhost:3000"
      VITE_WS_URL: "ws://localhost:3000/cable"

